/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import modeloBeans.ClasseAgendamento;
import modeloBeans.ClassePaciente;
import modeloBeans.ClasseCadastro;
import modeloConection.ConexaoBD;


public class TelaPrincipal extends javax.swing.JFrame {
 
    ClasseCadastro userLogado = null;
    String usuarioLogado;
    ConexaoBD conecta = new ConexaoBD();//Instanciando a classe conexão

    
    public TelaPrincipal(ClasseCadastro user, String usuario) {
        initComponents(); 
        userLogado = user;
        usuarioLogado =  usuario;
        conecta.getConnection();//Chama todo o método conexao da classe ConexaoBD
      
        jLabelUsuariologadoEquipeDeSaude.setText(usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButtonAgenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelUsuariologadoEquipeDeSaude = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelGerenciamento = new javax.swing.JLabel();
        jButtonSairBemVindo = new javax.swing.JButton();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBemVindo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setBackground(new java.awt.Color(13, 130, 203));
        jInternalFrameBemVindo.setTitle("Bem-Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternal.setBackground(new java.awt.Color(13, 130, 203));
        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agendateste.png"))); // NOI18N
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonAgenda);
        jButtonAgenda.setBounds(10, 60, 90, 100);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuário Logado:");
        jPanelInternal.add(jLabel2);
        jLabel2.setBounds(10, -10, 120, 50);

        jLabelUsuariologadoEquipeDeSaude.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelUsuariologadoEquipeDeSaude.setForeground(new java.awt.Color(255, 255, 255));
        jPanelInternal.add(jLabelUsuariologadoEquipeDeSaude);
        jLabelUsuariologadoEquipeDeSaude.setBounds(130, 0, 110, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agendateste2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButton1);
        jButton1.setBounds(110, 60, 90, 100);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PESQ.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButton2);
        jButton2.setBounds(210, 60, 90, 100);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Forum.png"))); // NOI18N
        jPanelInternal.add(jButton3);
        jButton3.setBounds(310, 60, 90, 100);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 40, 410, 180);

        jLabelGerenciamento.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabelGerenciamento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGerenciamento.setText("SISTEMA DE GERENCIAMENTO DE: ");
        jInternalFrameBemVindo.getContentPane().add(jLabelGerenciamento);
        jLabelGerenciamento.setBounds(10, 10, 300, 23);

        jButtonSairBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shut-down.png"))); // NOI18N
        jButtonSairBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairBemVindoActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonSairBemVindo);
        jButtonSairBemVindo.setBounds(350, 0, 40, 30);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(160, 100, 430, 250);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoView1.png"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, -20, 710, 480);

        jMenuCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu_1.png"))); // NOI18N
        jMenuCadastro.setText("Funções");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agendateste.png"))); // NOI18N
        jMenuItem1.setText("Registrar agendamento");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/agendateste2.png"))); // NOI18N
        jMenuItem2.setText("Cadastrar Teste COVID-19");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PESQ.png"))); // NOI18N
        jMenuItem4.setText("Visualizar Pacientes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Forum.png"))); // NOI18N
        jMenuItem5.setText("Enviar mensagens Fórum");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItem5);

        jMenuBar1.add(jMenuCadastro);

        jMenuFerramentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ferramenta.png"))); // NOI18N
        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBemVindo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemTelaBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Menu inicial.gif"))); // NOI18N
        jMenuItemTelaBemVindo.setText("Bem-Vindo");
        jMenuItemTelaBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBemVindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBemVindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Teste_2.png"))); // NOI18N
        jMenu3.setText("Mais");

        jMenuItem6.setText("Tela Login");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/information_finish.png"))); // NOI18N
        jMenu1.setText("Sobre");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Criadores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair.png"))); // NOI18N
        jMenuSair.setText("Sair");

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(726, 514));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairBemVindoActionPerformed
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonSairBemVindoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemTelaBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBemVindoActionPerformed
        jInternalFrameBemVindo.setVisible(true);

    }//GEN-LAST:event_jMenuItemTelaBemVindoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

        ViewCriadores mostra = new ViewCriadores();
        mostra.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        ViewRegistrarAgendamento agendar = new ViewRegistrarAgendamento(usuarioLogado);
        agendar.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ViewRegistrarTesteDoAgendamento regitrarTeste = new ViewRegistrarTesteDoAgendamento(usuarioLogado);
        regitrarTeste.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ViewVisualizarPacientes visualizar = new ViewVisualizarPacientes(usuarioLogado);
        visualizar.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ViewEnviarMensagens enviarMensagens = new ViewEnviarMensagens(usuarioLogado);
        enviarMensagens.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        ViewRegistrarAgendamento mostra = new ViewRegistrarAgendamento(usuarioLogado);
        mostra.setVisible(true);
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ViewRegistrarTesteDoAgendamento mostra = new ViewRegistrarTesteDoAgendamento(usuarioLogado);
        mostra.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ViewVisualizarPacientes visualizar = new ViewVisualizarPacientes(usuarioLogado);
        visualizar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ViewLogin login = new ViewLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    /**
     * @param args the command line arguments
     */
  


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonSairBemVindo;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelGerenciamento;
    public javax.swing.JLabel jLabelUsuariologadoEquipeDeSaude;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBemVindo;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}



























